### ISSUE TITLE
Android Studio 3 - built-in Java features

### ISSUE THREAD

**Issue by adek** [VictorAlbertos/ReactiveCache#17]
I'm using your library. I'm testing new tools in Android Studio 3 Canary 1. We've got finally possibility to use Java8 built-in features without using for example retrolamda library.

My app is crashing on ReactiveCache using AS3 Java8 built-in features.

Is retrolambda dependency for this library mandatory? 

     java.lang.NoSuchMethodError: No static method lambda$replace$2(Lio/reactivecache2/Provider;Lio/reactivex/Single;)Lio/reactivex/SingleSource; in class Lio/reactivecache2/Provider; or its super classes (declaration of 'io.reactivecache2.Provider' appears in /data/app/.../split_lib_dependencies_apk.apk)
                                                                      at io.reactivecache2.Provider$$Lambda$2.apply(Unknown Source)
at io.reactivex.Single.compose(Single.java:1548)

Not sure right now if this is AS3 bug or ReactiveCache. I'm still investingating this.

**Comment by stefan-zobel** [comment]
FWIW, this seems to be a bug in the Gradle Java 8 language feature desugaring that is tracked in https://issuetracker.google.com/issues/62456849
