### ISSUE TITLE
Q: read item with key

### ISSUE THREAD

**Issue by jemshit** [VictorAlbertos/ReactiveCache#18]
How to read `Event` item lets say, with key ? In readme, i can only see `cacheProvider.read()` which does not take key. As i understand, there are two keys? in this library, one for `cacheProvider` like "event", another for `item` itself like "1243". Is that correct

**Comment by VictorAlbertos** [comment]
You can use `ProviderGroup` for that. 

```java
ProviderGroup<List<Model>> cacheProvider =
		reactiveCache.<List<Model>>providerGroup()
        .withKey("modelsPaginated")

api.getModels(group)
	.compose(cacheProvider.replace(group))
```
