### ISSUE TITLE
Issues with encrypt 

### ISSUE THREAD

**Issue by NaSOS** [VictorAlbertos/ReactiveCache#19]
Hello, I am trying to enable encryption but when I do the cache is not working and constantly loads data from the network. 

What am I doing:

```
@Provides @Singleton fun provideCache(@ApplicationContext context: Context): ReactiveCache =
            ReactiveCache.Builder()
                    .encrypt("test")
                    .useExpiredDataWhenNoLoaderAvailable()
                    .using(context.filesDir, MoshiSpeaker())
```

And for the provider:
```
private val cacheProvider: ProviderList<Ingredient> = reactiveCache.providerList<Ingredient>()
            .encrypt(true)
            .lifeCache(1, TimeUnit.DAYS)
            .withKey("ingredients")
```

I tried to debug a bit in case I was doing something wrong and I noticed that during `Disk.retrieveRecord()` the `File` passed to `jolyglot` was not properly decrypted and as a result the json parsing was failing with:
```
java.lang.RuntimeException: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
``` 

I am attaching a screenshot of the `MoshiSpeaker.fromJson` where it shows that the `BufferedSource` passed to `JsonReader` is not valid.
<img width="1413" alt="screen shot 2017-11-19 at 13 57 21" src="https://user-images.githubusercontent.com/1401011/32990411-9f13086c-cd31-11e7-9fee-c10c2c21e950.png">

Can you please help?
Thanks a lot!!

**Comment by VictorAlbertos** [comment]
Please @miguelbcr can you take a look this?

**Comment by The0ldM0nk** [comment]
I concur with @NaSOS 🛠

**Comment by The0ldM0nk** [comment]
@VictorAlbertos @miguelbcr any update on this guys? Thanks!

**Comment by VictorAlbertos** [comment]
Sorry we have no time to actively maintain this library anymore, but feel free to collaborate fixing this issue by opening a PR 👍
