### ISSUE TITLE
Route not caching if empty list

### ISSUE THREAD

**Issue by PaulWoitaschek** [VictorAlbertos/ReactiveCache#8]
After debugging like forever I found out why the load on one of the backend routes is significantly larger.

I think I found the issue. If the cache type is a `List<WhatEver>` and an empty list is returned no `dataClassName` can be determined and thus the cache does not work.

**Comment by VictorAlbertos** [comment]
I think it was pointed out in a [RxCache issue](https://github.com/VictorAlbertos/RxCache/issues/61)

**Comment by PaulWoitaschek** [comment]
Can you change the internals? This is a huge bug.

**Comment by VictorAlbertos** [comment]
That's your opinion. 

But if there is no cached  data, it makes sense to me that RxCache tries again to retrieve data from its provider. That's the way RxCache has been working from the beginning, and I'm not willing to change it. 

As a workaround, you can always cache some flag to prevent calling RxCache.

**Comment by PaulWoitaschek** [comment]
An empty list does not mean "no data". When I say getMessages the server will repeat with an empty list of there are no messages and with a 40x if there is a problem. For me it absolutely make sense to cache that response. 

Btw as a workaround I just wrapped the list in a holder object that just wraps the list.

**Comment by PaulWoitaschek** [comment]
Sorry but this is still bugging me.

When I say `api.getNotes()` and the server returns an empty array, that is something I want to cache. I don't want to make hundreds of network calls.

**Comment by VictorAlbertos** [comment]
Sorry @PaulWoitaschek but right now I have no time to spend on this. Do you care to submit a PR? I'm only willing to change this behaviour for ReactiveCache, without touching the core shared with RxCache. Thanks for your constantly feedback, anyway.
